apiVersion: apps/v1
kind: Deployment
metadata:
  name: recall-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recall-app
  template:
    metadata:
      labels:
        app: recall-app # this can be any name but make sure it matches with the label selector in service.yaml file, its used by jenkins pipeline to run tests and health checks
    spec:
      containers:
      - name: recall-app
        image: farhanrhine/recall-ai-agent-gcp:v5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # this is the port your app listens to, make sure it matches with your app configuration, its used by jenkins pipeline to run tests and health checks
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: APP_HOST
          value: "0.0.0.0"
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY

