apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  selector:
    app: llmops-app
  ports:
    - port: 80
      targetPort: 8080  # port for AI Tutor SFA Pro
  type: NodePort